### PR TITLE
Whitespace fix

### PR DESCRIPTION
**Pull request by puppetpies**
Now as 1 commit !

Have a good weekend.

Regards,

Brian Hood

### CODE REVIEW

**Review by maiha — CHANGES_REQUESTED** [review]
It seems there are 3 commits :) Please try again!

FYI: After merging commits, you can override this PR by following command rather than create a new PR!
`git push -f origin whitespacefix`

Thanks.

**Comment by puppetpies** [comment]
Just tried didn't work !

**Comment by maiha** [comment]
Oh, it would be the git remote name is not `origin`.
Can you push `-f` ?

If so, could you see remote name in `.git/config` on your local repository.

```
[remote "origin"]
        url = git@github.com:puppetpies/pcap.cr.git
```

In above case, remote name is `origin`.

**Comment by maiha** [comment]
Or, failed at merging phase?

**Comment by puppetpies** [comment]
Well i created another PR just easier !

**Comment by maiha** [comment]
okay!

**Pull request closed without merging**
