### PR TITLE
Added set_promisc

### PR DESCRIPTION
**Pull request by puppetpies**
Added confirmation of options on start up of sniffer nicer.

Also the -p options is the same as tshark the -p port number was a bit pointless and that is what -f is for anyway.

See what you think.

### CODE REVIEW

**Comment by maiha** [comment]
Hi, Brian!
It seems that we can split into three issues.
1. new feature: set_promisc
   Thanks! I'd like to merge it!
2. better output
   I'm afraid that it's too much output especially with `-d` option that aims at minimum output.
3. changing `-p` option
   This is not good. Because I use `-p` many times in a day.
   Sorry for personal reason :) 

Thought?

**Comment by puppetpies** [comment]
Well merge the 1st / feature and leave out 2 & 3

**Comment by maiha** [comment]
Ok! Could you `push -f` this PR for the 1st?
Or, I'll create it ASAP (maybe within a few days)

**Comment by puppetpies** [comment]
Ok reverted 2 / 3 and added the Feature !

**Comment by maiha** [comment]
Thanks!

**Pull request merged**
